#!/usr/bin/env python3
"""visual_diff.py - build an HTML thumbnail gallery of test diff PNGs.

Walks tests/out/*.diff.png and produces tests/visual_diff.html: one row
per snippet, with thumbnails of the PS render, SVG render, and pixel
diff side by side. Indexed by snippet name for quick eyeballing.

Stdlib only; no image manipulation, just <img> tags. Diff PNGs are
linked relative to the report file (which lives in tests/) so the
output is portable inside the repo.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT_DIR = HERE / 'out'
REPORT = HERE / 'visual_diff.html'


def _read_results() -> dict[str, dict]:
    """Best-effort read of compare.py's results.json keyed by snippet name."""
    path = OUT_DIR / 'results.json'
    if not path.is_file():
        return {}
    try:
        with open(path, encoding='utf-8') as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}
    # results.json shape: {"snippets": [{"name": "...", "status": "...", "ae": ...}, ...]}
    rows = data.get('snippets') or data.get('results') or []
    return {r.get('name'): r for r in rows if r.get('name')}


def _img_or_missing(rel: str) -> str:
    """Return <img> tag if the referenced file exists, else a placeholder."""
    abs_p = HERE / rel
    if abs_p.is_file() and abs_p.stat().st_size > 0:
        return f'<img src="{rel}" loading="lazy" alt="{rel}">'
    return '<span class="missing">(missing)</span>'


def main() -> int:
    if not OUT_DIR.is_dir():
        print(f'visual_diff: {OUT_DIR} does not exist; run tests/run_all.sh first',
              file=sys.stderr)
        return 1

    diffs = sorted(OUT_DIR.glob('*.diff.png'))
    if not diffs:
        print(f'visual_diff: no .diff.png files in {OUT_DIR}', file=sys.stderr)
        return 1

    results = _read_results()

    rows: list[str] = []
    for diff_path in diffs:
        name = diff_path.name[:-len('.diff.png')]
        ps_png = f'out/{name}.ps.png'
        svg_png = f'out/{name}.svg.norm.png'
        diff_png = f'out/{name}.diff.png'

        meta = results.get(name, {})
        status = meta.get('status', '?')
        ae = meta.get('ae', '-')
        ssim = meta.get('ssim')
        badges = [f'<span class="badge status-{status.lower()}">{status}</span>',
                  f'<span class="badge">AE={ae}</span>']
        if ssim is not None:
            badges.append(f'<span class="badge">SSIM={ssim:.3f}</span>')

        rows.append(f"""\
<section class="snippet" id="{name}">
  <h2><a href="#{name}">{name}</a> {' '.join(badges)}</h2>
  <div class="grid">
    <figure><figcaption>PostScript</figcaption>{_img_or_missing(ps_png)}</figure>
    <figure><figcaption>SVG (normalised)</figcaption>{_img_or_missing(svg_png)}</figure>
    <figure><figcaption>diff</figcaption>{_img_or_missing(diff_png)}</figure>
  </div>
</section>""")

    html = f"""<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<title>mdlout visual diff</title>
<style>
body{{font-family:system-ui,sans-serif;margin:1em;background:#fafafa;color:#222}}
h1{{margin:0 0 0.5em}}
.snippet{{background:#fff;border:1px solid #ddd;border-radius:6px;
         padding:0.6em 0.8em;margin:0.8em 0;
         box-shadow:0 1px 2px rgba(0,0,0,0.05)}}
.snippet h2{{font-size:1em;margin:0 0 0.4em;font-family:ui-monospace,monospace}}
.snippet h2 a{{color:#333;text-decoration:none}}
.snippet h2 a:hover{{text-decoration:underline}}
.grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:0.5em}}
figure{{margin:0;padding:0;text-align:center}}
figcaption{{font-size:0.8em;color:#666;margin-bottom:0.3em}}
img{{max-width:100%;height:auto;border:1px solid #eee;background:#fff}}
.badge{{display:inline-block;padding:0.05em 0.5em;margin-left:0.3em;
       border-radius:3px;background:#eee;font-size:0.75em;
       font-family:ui-monospace,monospace;color:#444}}
.status-ok{{background:#d8f0d8;color:#2a6}}
.status-ps_fail,.status-svg_fail,.status-gs_fail,.status-rsvg_fail{{
   background:#fde0e0;color:#a33}}
nav{{margin:0.5em 0;font-family:ui-monospace,monospace;font-size:0.85em}}
nav a{{margin-right:0.5em;color:#06c}}
.missing{{color:#a33;font-style:italic}}
</style>
</head><body>
<h1>mdlout snippet visual diff</h1>
<p>{len(rows)} snippet(s). Generated by <code>tests/visual_diff.py</code>.</p>
<nav>{' '.join(f'<a href="#{d.name[:-len(".diff.png")]}">{d.name[:-len(".diff.png")]}</a>' for d in diffs)}</nav>
{os.linesep.join(rows)}
</body></html>
"""

    REPORT.write_text(html, encoding='utf-8')
    print(REPORT)
    return 0


if __name__ == '__main__':
    sys.exit(main())
